# Site settings
title: Mark Gross
lang: en-US # default lang
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Mark Gross
  bio: >- # tell to the world
    A student and programmer. Check out the posts below to see what I'm up to.
  github: MarkusG # github username
  twitter: Mark__Gross # twitter username
  avatar: /assets/img/avatar.png # change with your own avatar

# URL settings
url: "https://markgross.me" #
permalink: /:title/

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 5

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
